config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/Contact'
  get 'static_pages/Terms'
  root 'items#index' 
  resources :items,:path => "/Catalogue_chat"
  resources :carts,:path => "/Mon_Panier", only: [:create, :update, :destroy, :show]
  resources :orders,:path => "/Mes_commandes"
  devise_for :users,:path => "/Mon_Profil"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  
  namespace :admin do
    root to: 'static_pages#index'
    resources :users
    resources :items
    resources :orders, only: [:index, :show]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  after_create :order_confirm_user
  after_create :order_confirm_admin
  belongs_to :user
  has_and_belongs_to_many :items

  private
  
  def price_update
    total = 0
    self.items.each { |item| total += item.price }
    self.update(price: total)
  end

  def order_confirm_user
    UserMailer.user_order(self).deliver_now
  end

  def order_confirm_admin
    UserMailer.admin_checkorder(self).deliver_now
  end

end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    before_action :is_admin?

    def index
      @orders = Order.order(id: :desc)
    end

    def show
      @order = Order.find(params[:id])
    end
   
    private

    def is_admin?
      unless user_signed_in? && current_user.admin
        flash[:danger] = "Vous n'avez pas la permission d'accéder à cette page"
        redirect_to root_path
      end
    end
  end
end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def create
  end

  def show
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/admin/orders/index.html.erb
<h2>Commandes enregistrées</h2>
<h5>Recettes totales : <%= total_amount %> €</h5>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Date</th>
      <th scope="col">Client ID</th>
      <th scope="col">Nb articles</th>
      <th scope="col">Total</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
        <tr>
        <th><%= order.id %></th>
        <th><%= order.created_at.strftime('%e %b %Y') %></th>
        <th><%= order.user.id %></th>
        <th><%= order.items.count %></th>
        <th><%= order.price %></th>
        <th><%= link_to 'Afficher', admin_order_path(order), class: 'btn btn-primary btn-sm' %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<h2>Affichage de la commande n°<%= @order.id %></h2>
  <p>Commande passée le <%= @order.created_at.strftime('%e %b %Y à %H:%M:%S') %><br>
    ID Client : <%= @order.user.id %><br>
    Email : <%= @order.user.email %>
  </p>
<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">ID Item</th>
      <th scope="col">Titre</th>
      <th scope="col">Prix</th>
    </tr>
  </thead>
  <tbody>
      <% @order.items.each do |item| %>
    <tr>
      <th><%= item.id %></th>
      <th><%= item.title %></th>
      <th><%= item.price %></th>
      <th><%= link_to 'Afficher', admin_item_path(item), class: 'btn btn-primary btn-sm' %></th>
    </tr>
      <% end %>
  </tbody>
</table>
<h4>Total : <%= @order.price %> €</h4>