config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/Contact'
  get 'static_pages/Terms'
  root 'items#index' 
  resources :items,:path => "/Catalogue_chat"
  resources :carts,:path => "/Mon_Panier", only: [:create, :update, :destroy, :show]
  resources :orders,:path => "/Mes_commandes"
  devise_for :users,:path => "/Mon_Profil"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  
  namespace :admin do
    root to: 'static_pages#index'
    resources :users
    resources :items
    resources :orders, only: [:index, :show]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { in: 5..500}
  validates :price, presence: true

  
  has_and_belongs_to_many :carts
  has_and_belongs_to_many :orders

  has_many :users, through: :orders
  has_one_attached :picture

end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < AdminController
    before_action :is_admin?

    def index
      @items = Item.order(:id)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(
      title: params[:title],
      description: params[:description],
      price: params[:price],
      available: params[:available]
      )
      if @item.save
        @item.picture.attach(params[:picture])
        flash[:success] = "Le produit a bien été ajouté."
        redirect_to(admin_items_path)
      else
        flash[:warning] = "Il y a eu un problème lors de la création du produit."
        render new_admin_item_path
      end
    end  

    def show
      @item = Item.find(params[:id])
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      if @item.update!(item_params)
        flash[:success] = "Le produit a bien été mis à jour."
        redirect_to admin_items_path
      else
        flash[:warning] = "Il y a eu un problème lors de la mise à jour du produit"
        render 'edit'
      end
    end
    
    def destroy
      @item = Item.find(params[:id])
      if @item.destroy
        flash[:success] = "Le produit a bien été supprimé."
        redirect_to admin_items_path
      else
        flash[:warning] = "Il y a eu un problème lors de la suppression"
        redirect_to admin_items_path
      end
    end

    private

    def item_params
      params.require(:item).permit(:title, :description, :price, :picture, :available)
    end
  
    def is_admin?
      unless user_signed_in? && current_user.admin
        flash[:danger] = "Vous n'avez pas la permission d'accéder à cette page"
        redirect_to root_path
      end
    end
  end
end
  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.where(available: true)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price)
    end
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> interdit l'enregistrement de cet élément:</h2>
      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<%= render "layouts/banner"%>

<div class="container mt-5">
 <div class="row row-cols-1 row-cols-md-3 g-4">
  <% @items.each do |item| %>
   <div class="col">
    <a href="<%= item_path(item) %>">
     <div class="card bg-dark text-white text-decoration-none shadow">
      <%= image_tag item.picture, alt: item.title, class: "card-img img-index img-fluid" %>
      <div class="card-img-overlay text-center">
        <div class="btn btn-outline-alert btn-lg position-absolute bottom-0 start-50 translate-middle-x fw-bolder">
          <%= "#{item.price} €"%> <i class="fas fa-info-circle"></i>
        </div>
      </div>
     </div>
    </a>
   </div>
  <% end %>
 </div>
</div>

app/views/items/new.html.erb
<h1>Création d'un item</h1>

<%= form_tag url_for(action: 'create'), multipart: true do %>
    
  <%= label_tag 'Titre' %><br />
  <%= text_field_tag 'title', @item.title %><br />

  <%= label_tag 'Description' %><br />
  <%= text_field_tag 'description', @item.description %><br />

  <%= label_tag 'Prix' %><br />
  <%= text_field_tag 'price', @item.price %><br />

  <%= file_field_tag :picture %>

  <%= submit_tag "C'est parti" %>
<% end %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center align-items-center flex-column text-center col-12" style="height:70vh">
    <div class="card border-secondary mb-3">
      <div class="media d-flex justify-content-center">
        <a href="<%= @item.image_url %>" class="d-block">
          <%if @item.picture.attached?%>
            <%= image_tag @item.picture, alt: @item.title, class: "img-fluid", style: "max-height: 300px" %>
          <%else%>
            <p>=== Il n'y a pas de photo attachée au produit ===</p>
          <%end%>
        </a>
        <div class="media-body d-flex flex-column justify-content-between p-4 p-md-5">
          <h3><%= @item.title %></h3>
          <em><%= @item.description %></em>
          <br>
          <strong><%= @item.price %> <i class="fab fa-bitcoin"></i></strong>
          <% if user_signed_in? %>
            <%= link_to "Ajouter à mon panier", user_signed_in? ? cart_path(@item) : new_user_session_path, method: :put, class: "btn btn-outline-primary my-3" %>
          <% else %>
            <%= link_to "Ajouter à mon panier", new_user_session_path, class: "btn btn-outline-primary my-3" %>
          <% end %>
        </div>
      </div>
    </div>
   <br>
  <%= link_to 'Retour à l\'accueil', items_path %>
</div>