config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/Contact'
  get 'static_pages/Terms'
  root 'items#index' 
  resources :items,:path => "/Catalogue_chat"
  resources :carts,:path => "/Mon_Panier", only: [:create, :update, :destroy, :show]
  resources :orders,:path => "/Mes_commandes"
  devise_for :users,:path => "/Mon_Profil"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  
  namespace :admin do
    root to: 'static_pages#index'
    resources :users
    resources :items
    resources :orders, only: [:index, :show]
  end

end

app/controllers/admin/static_pages_controller.rb
module Admin

  class StaticPagesController < AdminController
    before_action :is_admin?

    def index
    end

    def is_admin?
      unless user_signed_in? && current_user.admin
        flash[:danger] = "Vous n'avez pas la permission d'accéder à cette page"
        redirect_to root_path
      end
    end
    
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  
  def Contact
  end

  def Terms
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/index.html.erb
<h1>Console Administrateur</h1>
<h3>Ravi de vous revoir <%= current_user.email %> !</h3>

<div class="row">
  <div class="col-sm-4">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title"><%= User.count %></h1>
        <p class="card-text">Utilisateurs inscrits</p>
        <%= link_to 'Gestion utilisateurs', admin_users_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title"><%= average_cart_amount %> €</h1>
        <p class="card-text">Panier moyen</p>
        <%= link_to 'Gestion des commandes', admin_orders_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title"><%= Item.count %></h1>
        <p class="card-text">Articles en vente</p>
        <%= link_to 'Gestion items en vente', admin_items_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>